# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - megalt-container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_7bce56d981b74844bbcf9203ba79b99a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_de8ff0843a7243b2a3b38fe856ea9427 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7bce56d981b74844bbcf9203ba79b99a }}/megalt-api-training:${{ github.sha }}
        file: ./MegaLTAPI1/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'megalt-container'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0bbff476d5144b30aa43731e8e7cc51d }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_7bce56d981b74844bbcf9203ba79b99a }}/megalt-api-training:${{ github.sha }}'
